{
  description = "AI OS - Strix Halo inference node (llama-server on Vulkan/RADV + Hermes Agent)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Hermes Agent ships its own flake with a full NixOS module.
    # Nix/NixOS is a Tier 2 platform for Hermes (best-effort), so pin and
    # update deliberately rather than tracking main blindly.
    hermes-agent.url = "github:NousResearch/hermes-agent";

    # OPTIONAL: gfx1151 packages built against the TheRock ROCm SDK
    # (llama-cpp-rocm, llama-cpp-master-vulkan, vllm-rocm, live-iso).
    # Upstream explicitly states pre-1.0 "no support / no warranty" and the
    # layout may change. Useful for ROCm A/B benchmarking; not required for
    # the core Vulkan path. Uncomment here and in the modules list to use.
    # nix-strix-halo.url = "github:hellas-ai/nix-strix-halo";
  };

  outputs = { self, nixpkgs, hermes-agent, ... }@inputs: {
    nixosConfigurations.ai-os = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      specialArgs = { inherit inputs; };
      modules = [
        # Generated by nixos-generate-config during install. Copy it into
        # this repo next to flake.nix.
        ./hardware-configuration.nix

        ./configuration.nix
        ./modules/strix-halo.nix
        ./modules/llama-server.nix
        ./modules/hermes.nix
        ./modules/hermes-context.nix
        ./modules/claude-code.nix
        ./modules/claude-bridge.nix
        ./modules/local-planner.nix

        hermes-agent.nixosModules.default

        # inputs.nix-strix-halo.nixosModules.default
      ];
    };
  };
}
